apiVersion: tpokki.github.com/v1alpha1
kind: GatlingTask
metadata:
  name: example-gatlingtask
spec:
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 500M
    requests:
      cpu: 200m
      memory: 500M
  scenario:
    name: Example
    data:
      Example.scala: |
        import io.gatling.core.Predef._
        import io.gatling.http.Predef._
        import scala.concurrent.duration._

        class Example extends Simulation {

          val httpProtocol = http.baseUrl("http://computer-database.gatling.io")

            val scn = scenario("Example")
              .exec(
                http("request_1")
                  .get("/computers")
              )
              .pause(60)

            setUp(scn.inject(atOnceUsers(1)).protocols(httpProtocol))
        }
