apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gatlingtasks.tpokki.github.com
spec:
  group: tpokki.github.com
  names:
    kind: GatlingTask
    listKind: GatlingTaskList
    plural: gatlingtasks
    singular: gatlingtask
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        description: GatlingTask is the Schema for the gatlingtasks API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: GatlingTaskSpec defines the desired state of GatlingTask
            type: object
            properties:
              replicas:
                type: integer
              resources:
                type: object
                properties:
                  limits:
                    type: object
                    properties:
                      memory:
                        type: string
                        pattern: ^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$
                      cpu:
                        type: string
                        pattern: ^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$
                  requests:
                    type: object
                    properties:
                      memory:
                        type: string
                        pattern: ^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$
                      cpu:
                        type: string
                        pattern: ^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$
              scenario:
                type: object
                properties:
                  name:
                    type: string
                  data:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
          status:
            description: GatlingTaskStatus defines the observed state of GatlingTask
            type: object
        type: object
